name: "PR Labeler"
on:
  - pull_request_target

jobs:
  labeler:
    if: contains(fromJSON('["folke", "LazyVim"]'), github.repository_owner)
    uses: folke/github/.github/workflows/labeler.yml@main
    secrets: inherit
