#!/bin/env bash

set -e

repos=$(gh repo list -L200 --source --no-archived --json nameWithOwner --jq ".[].nameWithOwner" | rg nvim | rg -v "plugin-tools" | sort)
repos="$repos folke/github LazyVim/LazyVim"
for repo in $repos; do
  echo "[$repo]"
  gh repo edit "$repo" --allow-update-branch --enable-discussions --enable-squash-merge --enable-rebase-merge --enable-merge-commit=false --enable-wiki
  gh api "repos/$repo/branches/main/protection" --method PUT --input scripts/branch-protection.json >/dev/null
  gh api "repos/$repo" --method PATCH -f "squash_merge_commit_title=PR_TITLE" -f "squash_merge_commit_message=PR_BODY" >/dev/null
done
